// A code grader's program must travel inside its manifest, and the Inngest
// worker is a serverless entry point where a runtime readFileSync of a source
// file is exactly what a bundler's file tracing drops. So each program's text
// is embedded in a checked-in module, and source.test.ts fails `pnpm check`
// when the two disagree. Run after editing any grader.mjs.
import { readFileSync, writeFileSync } from 'node:fs';

const CODE_GRADERS = ['test-discipline'];

for (const name of CODE_GRADERS) {
  const directory = `src/domain/grading/graders/${name}`;
  const source = readFileSync(`${directory}/grader.mjs`, 'utf8');
  writeFileSync(
    `${directory}/source.generated.ts`,
    `// Generated by \`pnpm graders:embed\` from grader.mjs. Do not edit by hand:\n// source.test.ts fails when this and grader.mjs disagree.\nexport const source = ${JSON.stringify(source)};\n`,
  );
}
